export function experienceTemplate(index) {
  return `<div class="experience-item" data-experience><button type="button" class="remove-experience" aria-label="Eliminar experiencia">Eliminar</button><div class="form-grid"><label>Empresa<input name="company-${index}" placeholder="Ej. Empresa S.A.S." /></label><label>Cargo<input name="job-${index}" placeholder="Ej. Asistente" /></label><label>Fecha inicial<input name="start-${index}" placeholder="Ej. Enero 2023" /></label><label>Fecha final<input name="end-${index}" placeholder="Ej. Actualidad" /></label><label class="span-all">Funciones realizadas<textarea name="tasks-${index}" placeholder="Describe tus funciones y logros."></textarea></label></div></div>`;
}
export function cvTemplate(data, experiences) {
  const education = [data.educationLevel, data.program, data.institution, data.educationYear].filter(Boolean).join(' · ');
  const list = (value) => value ? `<ul>${value.split(',').filter(Boolean).map(x => `<li>${escapeHtml(x.trim())}</li>`).join('')}</ul>` : '';
  const exp = experiences.filter(x => x.company || x.job || x.tasks).map(x => `<div><p class="item-title">${escapeHtml(x.job || 'Experiencia profesional')} ${x.company ? '— ' + escapeHtml(x.company) : ''}</p><p class="contact">${escapeHtml([x.start, x.end].filter(Boolean).join(' — '))}</p><p>${escapeHtml(x.tasks)}</p></div>`).join('') || '<p>Agrega tus experiencias para fortalecer esta sección.</p>';
  return `<h2>${escapeHtml(data.name)}</h2><p class="contact">${escapeHtml(data.city)} · ${escapeHtml(data.phone)} · ${escapeHtml(data.email)}</p><p class="cv-role">${escapeHtml(data.role)}</p><h3>Perfil profesional</h3><p>${escapeHtml(data.objective)}</p><h3>Experiencia</h3>${exp}<h3>Educación</h3><p>${escapeHtml(education || 'Información no registrada')}</p>${data.skills ? `<h3>Habilidades</h3>${list(data.skills)}` : ''}${data.languages ? `<h3>Idiomas</h3><p>${escapeHtml(data.languages)}</p>` : ''}${data.courses ? `<h3>Cursos y certificaciones</h3><p>${escapeHtml(data.courses)}</p>` : ''}`;
}
export function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;' }[char])); }
